### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by chomyeong** [MitI-7/IDEOM#2]
i'm sorry bro,how to use?

**Comment by MitI-7** [comment]
Sorry. IDEOM(ver 0.2) doesn't work at latest JetBrains IDE.
I'll fix it as soon as possible.

IDEOM(ver 0.2) work at 
- Intellij IDEA 15.0.6
- PyCharm 4.5.5
- PhpStorm 10.0.4,
  ...

**Comment by chomyeong** [comment]
thanks bro! i like your project.:D

**Comment by MitI-7** [comment]
@chomyeong 
I fix it.
You can get fixed version at https://github.com/MitI-7/IDEOM/releases/tag/0.2.1

IDEOM(ver 0.2.1) work at
- IntelliJ IDEA 2016.1.3 Build #IU-145.1617, built on June 3, 2016
- PhpStorm 2016.2 Build #PS-162.1121.38, built on July 12, 2016
- PyCharm 2016.1.4 Build #PY-145.1504, built on May 25, 2016

**Comment by chomyeong** [comment]
@MitI-7 wow! bro,it's great,thank you !  I can't wait to have a try.
i'm sorry bro,what 's the Icon image, and how to use two images background in phpstorm,please?

**Comment by MitI-7** [comment]
@chomyeong 
Icon image is image file(e.g. png) 
I added 'How To Use' to README.md. Please see that file.
If you have any other questions, please ask me.

**Comment by chomyeong** [comment]
@MitI-7 Thanks bro !:D
