### ISSUE TITLE
Editor setting: Files names are constraint to 19 characters long. 

### ISSUE THREAD

**Issue by RedLeader962** [MitI-7/IDEOM#3]
Files names are constraint to 19 characters long when you want to create or edit a **Editor setting** in the **Input Dialog** window (I'm using the plugin in PyCharm). 

It force us to use shorter file name witch is problematic!

At the 18th character
![capture d ecran 2017-08-31 a 09 19 26](https://user-images.githubusercontent.com/10325816/29925199-8b247e64-8e2d-11e7-906b-7d94c8c94886.png)

At the 19th character
![capture d ecran 2017-08-31 a 09 02 18](https://user-images.githubusercontent.com/10325816/29924496-20f0895e-8e2b-11e7-9a1c-322226cf299f.png)

Also, it would be cool to had support for folder name or if we could use regEx in the **Editor setting** in the **Input Dialog** so we can assign a **background option** to all files contained in a folder or all file matching the regEx.

Very nice plugin by the way! I use it to add visual cue so I can quickly switch between files I'm working on .
![capture d ecran 2017-08-31 a 10 31 38](https://user-images.githubusercontent.com/10325816/29928884-0ee407f6-8e38-11e7-921c-8264f6173eda.png)

Luc

**Comment by MitI-7** [comment]
* Constraint of the file name
I removed that constraint at ver 0.2.3.
please update to new version.

* regular expression
You can use regEx in the File Name.
If **File Name** in the **Editor Setting** is ".*\.py", it will work with all python files.

thx!

**Comment by RedLeader962** [comment]
good job
thanks!
