### ISSUE TITLE
Sound error: File of unsupported format

### ISSUE THREAD

**Issue by psyanite** [MitI-7/IDEOM#6]
Hi first thank you for making such an amazing plugin and maintain to be compatible with current version.

I tried using it but it's not working.

I tried both aac and mp3 files no work.
I even tried moving the files to different folders like my documents / my desktop / my download, still no work.
Maybe it is file path error???
The files play no problem in QuickTime player.

Also the front page of the Github Repository does not have instructions on how to enable sound.

When i click "Play" nothing happens
![Screen Shot 2021-12-21 at 11 45 46](https://user-images.githubusercontent.com/24215698/146851957-06d24111-fb2f-4355-9130-3329c983664f.png)

When I open project this is the error:
![Screen Shot 2021-12-21 at 11 43 07](https://user-images.githubusercontent.com/24215698/146852089-47983178-3e87-4876-80da-bb957fcb908d.png)

MacOS Mojave
Macbook Pro 15inch 2018

Thank you so much <3

**Comment by MitI-7** [comment]
Thank you for using the plugin.
I'm Sorry, but it only supports wav format.

**Comment by psyanite** [comment]
Hi @MitI-7, thank you so much 👍  
I'll give it a go!

**Comment by psyanite** [comment]
Thanks so much it works! 😄
